//
// Created by You, Zhengzhong on 8/2/24.
//

#ifndef INCLUDE_SOLVER_INTERFACE_MINDOPT_HPP_
#define INCLUDE_SOLVER_INTERFACE_MINDOPT_HPP_
#include "technique_control.hpp"

#if SOLVER_TYPE == 2
#include "Mindopt.h"
#include <cstddef>
#include <string>
using SOLVERmodel = MDOmodel;
using SOLVERenv = MDOenv;
#define SOLVER_EQUAL MDO_EQUAL
#define SOLVER_GREATER_EQUAL MDO_GREATER_EQUAL
#define SOLVER_LESS_EQUAL MDO_LESS_EQUAL
#define SOLVER_BINARY MDO_BINARY
#define SOLVER_INTEGER MDO_INTEGER
#define SOLVER_CONTINUOUS MDO_CONTINUOUS
#define SOLVER_INFEASIBLE 3
#define SOLVER_INF_OR_UNBD 4
#define SOLVER_UNBOUNDED 5
#define SOLVER_PRIMAL_SIMPLEX 0
#define SOLVER_DUAL_SIMPLEX 1
#define SOLVER_BARRIER 2
#define SOLVER_MAX_SENSE (-1)
#define SOLVER_TIME_LIMIT 9
#define SOLVER_MIP_INFEASIBLE MDO_INFEASIBLE
#define SOLVER_INFINITY MDO_INFINITY
#define SOLVER_OPTIMAL MDO_OPTIMAL
#define SOLVER_SUBOPTIMAL MDO_SUB_OPTIMAL
#endif
#endif //VRPTW_INCLUDE_SOLVER_INTERFACE_MINDOPT_HPP_
